#!/bin/sh
# Generic texts
declare -A _generic
_generic['invalid-call']='Invalid call to function *FUNCNAME[0]*'
_generic['invalid-parameter']='Invalid parameter $1 for function *FUNCNAME[0]*'
_generic['pluriel']='s'
_generic['abort']="Aborted"

# Per functions texts
declare -A _set_param
_set_param['param-error']='An error occurred while setting parameters'

declare -A _prepare_for_exit
_prepare_for_exit['canceled']='Cancelled *func*'

declare -A _zenity_emerge
_zenity_emerge['sync-title']='Syncing repositories'
_zenity_emerge['checkdep-title']='Preparing for cleaning'
_zenity_emerge['depclean-title']='Cleaning your system'
_zenity_emerge['check-title1']='Checking for upgrades'
_zenity_emerge['check-title2']='Checking for *UP* upgrade'
_zenity_emerge['upgrade-title1']='Upgrading your system'
_zenity_emerge['upgrade-title2']='Upgrading *UP*'
_zenity_emerge['upgrade-title3']='Upgrading *pack^*'
_zenity_emerge['sync-error']='An error occurred while syncing, please check logs'
_zenity_emerge['checkdep-error']='An error occurred while checking for obsolete packages, please check logs'
_zenity_emerge['depclean-error']='An error occurred while cleaning system, please check logs'
_zenity_emerge['check-error']='An error occurred while checking dependencies, please check logs'
_zenity_emerge['upgrade-error']='An error occurred while upgrading system, please check logs'
_zenity_emerge['eix-message']='Updating eix database'
_zenity_emerge['checkdep-message']='Checking for obsolete packages'
_zenity_emerge['check-message']='Calculating dependencies'
_zenity_emerge['upgrade-message']='Calculating upgrade'
_zenity_emerge['conf-title']='Configuration file needs update'
_zenity_emerge['package-title']='Messages for *package*'

declare -A _zenity_upgrade
_zenity_upgrade['unmerge-title']='*number* package*plur* should be unmerged'
_zenity_upgrade['merge-title']='*number* package*plur* should be merged'
_zenity_upgrade['conf-needed']='Some configuration is necessary to proceed'
_zenity_upgrade['uncheck-message']='Uncheck packages you want to exclude.'
#_zenity_upgrade['not-installed']='Some package*plur* won't be installed :'
_zenity_upgrade['est-merge']='Estimating merge time'
_zenity_upgrade['est-not-found']='Unknown merge time for *package[$i]*'
_zenity_upgrade['est-found']='Average merge time for *package[$i]* is *time_h[$i]*'
_zenity_upgrade['est-total']='Estimated merge time is'
#_zenity_upgrade['package-message']='*UP* needs update, it's highly recommended to do it first.'

# Script's specific texts